### PR TITLE
Upgrade to ids-enterprise-ng 5.0.0

### PR DESCRIPTION
**Pull request by bthharper**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Upgraded quickstart to `ids-enterprise-ng` 5.0.0

**Related github/jira issue (required)**:

N/A

**Steps necessary to review your pull request (required)**:

N/A

### CODE REVIEW

**Comment by bthharper** [comment]
Merged

**Comment by bthharper** [comment]
Merged

**Comment by bthharper** [comment]
@clepore - can I have the rights to merge this?

**Comment by clepore** [comment]
You do have the right permissions, weird that you can't.

**Comment by bthharper** [comment]
Odd - the button was greyed out and said I need permissions.

**Comment by clepore** [comment]
Okay. I made one tweak so we'll see for the next one. Ping me on Teams if it is still disabled and I can try playing with the settings again.

**Pull request merged**
